version: '3.8'

services:
  web:
    image: python:3.9-slim
    ports:
      - "8001:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    command: sh -c "cd /app && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
