version: '3.8'

services:
  web:
    image: python:3.9-slim
    ports:
      - "8001:8000"
    command: sh -c "pip install django>=4.2.19 gunicorn==21.2.0 && django-admin startproject app && cd app && python manage.py runserver 0.0.0.0:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
