# Generated by Django 4.2.19 on 2025-02-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Propertie',
        ),
    ]
