# Generated by Django 4.2.19 on 2025-02-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_properties_propertie'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
