# Generated by Django 4.2.19 on 2025-02-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertie',
            name='condoPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='propertie',
            name='infos',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='propertie',
            name='iptuPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertie',
            name='neighborhood',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertie',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='fullAddress',
            field=models.CharField(default='', max_length=250),
        ),
    ]
